### PR TITLE
Update index.html to use requirejs and load lib as AMD. Fix #1

### LINKED ISSUE #1: index.html references non-dist build
Great library! While exploring the project I found that the demo `index.html` doesn't load the dist build, and so it encounters the following error:

bezierizer.core.js:181 Uncaught SyntaxError: Illegal return statement

Initially, I just commented this line out and it worked. Then I reviewed your commits and found that you dropped non-amd support, so I think we can just update the index.html to load the `dist/...js` file.

### PR DESCRIPTION
**Pull request by evanjbowling**
This moves the index.html JS logic into a new requirejs module `main.js` and adds a requirejs config files `app.js`.

### CODE REVIEW

**Comment by evanjbowling** [comment]
This references issue #1

**Comment by jeremyckahn** [comment]
Thank you for making this change, @evanjbowling!  I probably won't have a chance to properly review or merge this today, but I will prioritize doing so for sometime this weekend.

**Comment by jeremyckahn** [comment]
Reviewed and merged.  Thank you very much for the fix! 🙌

**Comment by evanjbowling** [comment]
no problem :)

**Pull request merged**
